# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue! 
  Admin will get back to you soon.
  Meanwhile check [this](https://github.com/prathimacode-hub/Awesome_Python_Scripts) repo for more.
  
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Thanks for opening this pull request! 🤗
  **Are you looking for more beginner-friendly issues? Check out [this](https://github.com/prathimacode-hub/Awesome_Python_Scripts) repo.**
 
  Show some love by starring a few of my [projects](https://github.com/prathimacode-hub/prathimacode-hub/blob/main/PROJECTS.md).🚀
  
  PS: Please add @prathimacode-hub as a reviewer if you haven't added.
 
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  Congrats on merging your first pull request! 🙌🎉⚡️
  Show some love by starring a few of my [projects](https://github.com/prathimacode-hub/prathimacode-hub/blob/main/PROJECTS.md).🚀
